version: "3.8"
services:
  redis:
    image: redis:6.2.6
    command: redis-server --requirepass 12345
    volumes:
      - starter-redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"
    networks:
      - dev
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      driver: none
    ports:
      - "5438:5432"
    networks:
      - dev
    volumes:
      - starter-postgres-data:/var/lib/postgresql/data
networks:
  dev:
    driver: host
volumes:
  starter-postgres-data: {}
  starter-redis-data: {}